name: linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      
      - name: Run lint
        run: |
          make lint