name: test-check

on: push

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run test
        run: make test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: make test-coverage
          debug: true